# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: questionnaire
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9906:3306"
  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    volumes:
      - "./:/var/www/html/"
    ports:
      - "8100:80"